service: new-dogs-serverless-notifier

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1

iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
    Resource: "arn:aws:dynamodb:eu-west-1:${env:IAM_USER_ID}:table/dogs"

environment:
  TWILIO_ID: ${env:TWILIO_ID}
  TWILIO_TOKEN: ${env:TWILIO_TOKEN}
  TWILIO_FROM_PHONE_NUMBER: ${env:TWILIO_FROM_PHONE_NUMBER}
  TWILIO_TO_PHONE_NUMBER: ${env:TWILIO_TO_PHONE_NUMBER}

functions:
  scrapeDogs:
    handler: handler.scrapeDogs
    events:
      - schedule: rate(2 hours)
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

# Have to comment out the dynamoDB resource once the table has been created as otherwise deployment will error
# See https://stackoverflow.com/questions/41620437/how-to-continue-deploy-if-dynamodb-table-already-exists

# resources:
#   - ${file(resources/dynamo-db.yml)}