Resources:
  DogsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: dogs
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      # Set the capacity
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1